//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BackToTheDawnTrainer.Resources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Lang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Lang() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BackToTheDawnTrainer.Resources.Lang", typeof(Lang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 This constructor should only be used in design mode. 的本地化字符串。
        /// </summary>
        public static string Exception_ConstructorOnlyBeUsedInDesignMode {
            get {
                return ResourceManager.GetString("Exception_ConstructorOnlyBeUsedInDesignMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Il2CppDumper exited with code {0}. Please check the output for errors. 的本地化字符串。
        /// </summary>
        public static string Exception_DumperExitedNonZero {
            get {
                return ResourceManager.GetString("Exception_DumperExitedNonZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Game is not running. 的本地化字符串。
        /// </summary>
        public static string Exception_GameNotRunning {
            get {
                return ResourceManager.GetString("Exception_GameNotRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 LogHandler is not set. 的本地化字符串。
        /// </summary>
        public static string Exception_LoggerHandlerNotSet {
            get {
                return ResourceManager.GetString("Exception_LoggerHandlerNotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Method with signature {0} not found. 的本地化字符串。
        /// </summary>
        public static string Exception_MethodWithSignatureNotFound {
            get {
                return ResourceManager.GetString("Exception_MethodWithSignatureNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unable to find the base directory of the application. 的本地化字符串。
        /// </summary>
        public static string Exception_UnableToFindBaseDirectory {
            get {
                return ResourceManager.GetString("Exception_UnableToFindBaseDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please select the game directory. 的本地化字符串。
        /// </summary>
        public static string FolderBrowserDialogBrowse_Description {
            get {
                return ResourceManager.GetString("FolderBrowserDialogBrowse_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cancel 的本地化字符串。
        /// </summary>
        public static string GambleCardConfigureWindow_ButtonCancel_Content {
            get {
                return ResourceManager.GetString("GambleCardConfigureWindow_ButtonCancel_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Confirm 的本地化字符串。
        /// </summary>
        public static string GambleCardConfigureWindow_ButtonConfirm_Content {
            get {
                return ResourceManager.GetString("GambleCardConfigureWindow_ButtonConfirm_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Lock 的本地化字符串。
        /// </summary>
        public static string GambleCardConfigureWindow_CheckBoxLock_Content {
            get {
                return ResourceManager.GetString("GambleCardConfigureWindow_CheckBoxLock_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Warning 的本地化字符串。
        /// </summary>
        public static string GambleCardConfigureWindow_SuitNotSelected_Caption {
            get {
                return ResourceManager.GetString("GambleCardConfigureWindow_SuitNotSelected_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please set suit. 的本地化字符串。
        /// </summary>
        public static string GambleCardConfigureWindow_SuitNotSelected_Text {
            get {
                return ResourceManager.GetString("GambleCardConfigureWindow_SuitNotSelected_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Browse... 的本地化字符串。
        /// </summary>
        public static string MainWindow_ButtonBrowseGameDirectory_Content {
            get {
                return ResourceManager.GetString("MainWindow_ButtonBrowseGameDirectory_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Disable 的本地化字符串。
        /// </summary>
        public static string MainWindow_ButtonDisable_Content {
            get {
                return ResourceManager.GetString("MainWindow_ButtonDisable_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Enable 的本地化字符串。
        /// </summary>
        public static string MainWindow_ButtonEnable_Content {
            get {
                return ResourceManager.GetString("MainWindow_ButtonEnable_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Confirm 的本地化字符串。
        /// </summary>
        public static string MainWindow_ClosingConfirm_Caption {
            get {
                return ResourceManager.GetString("MainWindow_ClosingConfirm_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Trainer is still running. Are you sure you want to exit? 的本地化字符串。
        /// </summary>
        public static string MainWindow_ClosingConfirm_Text {
            get {
                return ResourceManager.GetString("MainWindow_ClosingConfirm_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Game Directory: 的本地化字符串。
        /// </summary>
        public static string MainWindow_LabelGameDirectory_Content {
            get {
                return ResourceManager.GetString("MainWindow_LabelGameDirectory_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [x] Game is not running 的本地化字符串。
        /// </summary>
        public static string MainWindow_LabelGameNotRunning_Content {
            get {
                return ResourceManager.GetString("MainWindow_LabelGameNotRunning_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [√] Game is running 的本地化字符串。
        /// </summary>
        public static string MainWindow_LabelGameRunning_Content {
            get {
                return ResourceManager.GetString("MainWindow_LabelGameRunning_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Dice 的本地化字符串。
        /// </summary>
        public static string MainWindow_TabDice_Header {
            get {
                return ResourceManager.GetString("MainWindow_TabDice_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Dice 1: 的本地化字符串。
        /// </summary>
        public static string MainWindow_TabDice_LabelDice1_Content {
            get {
                return ResourceManager.GetString("MainWindow_TabDice_LabelDice1_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Dice 2: 的本地化字符串。
        /// </summary>
        public static string MainWindow_TabDice_LabelDice2_Content {
            get {
                return ResourceManager.GetString("MainWindow_TabDice_LabelDice2_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Random 的本地化字符串。
        /// </summary>
        public static string MainWindow_TabDice_RadioButtonDice_Random {
            get {
                return ResourceManager.GetString("MainWindow_TabDice_RadioButtonDice_Random", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Gamble 的本地化字符串。
        /// </summary>
        public static string MainWindow_TabGamble_Header {
            get {
                return ResourceManager.GetString("MainWindow_TabGamble_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Self: 的本地化字符串。
        /// </summary>
        public static string MainWindow_TabGamble_LabelPlayer1_Content {
            get {
                return ResourceManager.GetString("MainWindow_TabGamble_LabelPlayer1_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Player 2: 的本地化字符串。
        /// </summary>
        public static string MainWindow_TabGamble_LabelPlayer2_Content {
            get {
                return ResourceManager.GetString("MainWindow_TabGamble_LabelPlayer2_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Player 3: 的本地化字符串。
        /// </summary>
        public static string MainWindow_TabGamble_LabelPlayer3_Content {
            get {
                return ResourceManager.GetString("MainWindow_TabGamble_LabelPlayer3_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Player 4: 的本地化字符串。
        /// </summary>
        public static string MainWindow_TabGamble_LabelPlayer4_Content {
            get {
                return ResourceManager.GetString("MainWindow_TabGamble_LabelPlayer4_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Back To The Dawn Trainer 的本地化字符串。
        /// </summary>
        public static string MainWindow_Title {
            get {
                return ResourceManager.GetString("MainWindow_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No local device found. 的本地化字符串。
        /// </summary>
        public static string Trainer_NoLocalDeviceFound {
            get {
                return ResourceManager.GetString("Trainer_NoLocalDeviceFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unable to find process with PID {0}. 的本地化字符串。
        /// </summary>
        public static string Trainer_ProcessWithPidNotFound {
            get {
                return ResourceManager.GetString("Trainer_ProcessWithPidNotFound", resourceCulture);
            }
        }
    }
}
